include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-simple-xray
PKG_VERSION:=0.1
PKG_RELEASE:=1
LUCI_TITLE:=LuCI app for xray
LUCI_DEPENDS:=+xray-core

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Quanljh <quanljh@gmail.com>

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
